Fuel Injection Perfection
=========================

Commander Lambda has asked for your help to refine the automatic quantum antimatter fuel injection system for her LAMBCHOP doomsday device. It's a great chance for you to get a closer look at the LAMBCHOP - and maybe sneak in a bit of sabotage while you're at it - so you took the job gladly. 

Quantum antimatter fuel comes in small pellets, which is convenient since the many moving parts of the LAMBCHOP each need to be fed fuel one pellet at a time. However, minions dump pellets in bulk into the fuel intake. You need to figure out the most efficient way to sort and shift the pellets down to a single pellet at a time. 

The fuel control mechanisms have three operations: 

1) Add one fuel pellet
2) Remove one fuel pellet
3) Divide the entire group of fuel pellets by 2 (due to the destructive energy released when a quantum antimatter pellet is cut in half, the safety controls will only allow this to happen if there is an even number of pellets)

Write a function called answer(n) which takes a positive integer as a string and returns the minimum number of operations needed to transform the number of pellets to 1. The fuel intake control panel can only display a number up to 309 digits long, so there won't ever be more pellets than you can express in that many digits.

For example:
answer(4) returns 2: 4 -> 2 -> 1
answer(15) returns 5: 15 -> 16 -> 8 -> 4 -> 2 -> 1


Languages
=========

To provide a Python solution, edit solution.py
To provide a Java solution, edit solution.java

Test cases
==========

Inputs:
    (string) n = "4"
Output:
    (int) 2

Inputs:
    (string) n = "15"
Output:
    (int) 5

In [1]:
def answer(n):
    
    current = int(n)
    n_operations = 0
    
    if n == 1:
        return 1
    
    while current != 1:
    
        if current == 1:
            break

        elif current%2 == 0:
            
            current = current / 2
            n_operations += 1
#             print(current*2,"(/2)  ", current, n_operations)
            
        elif current%2 == 1:
            
            if ((current-1)/2) % 2 == 0 or (current-1)/2 == 1:
                
                current -= 1
                n_operations += 1
#                 print(current+1, "(-1)  ", current, n_operations)
            
            elif ((current+1)/2) % 2 == 0:
                
                current += 1
                n_operations += 1
#                 print(current-1, "(+1)  ", current, n_operations)
            
#     print("Total # operations:", n_operations)
    return n_operations

In [2]:
answer(15)

5

In [3]:
answer(25)

6

In [4]:
answer(6)

3

In [5]:
answer(11)

5

In [6]:
answer(3)

2

Prepare the Bunnies' Escape
===========================

You're awfully close to destroying the LAMBCHOP doomsday device and freeing Commander Lambda's bunny prisoners, but once they're free of the prison blocks, the bunnies are going to need to escape Lambda's space station via the escape pods as quickly as possible. Unfortunately, the halls of the space station are a maze of corridors and dead ends that will be a deathtrap for the escaping bunnies. Fortunately, Commander Lambda has put you in charge of a remodeling project that will give you the opportunity to make things a little easier for the bunnies. Unfortunately (again), you can't just remove all obstacles between the bunnies and the escape pods - at most you can remove one wall per escape pod path, both to maintain structural integrity of the station and to avoid arousing Commander Lambda's suspicions. 

You have maps of parts of the space station, each starting at a prison exit and ending at the door to an escape pod. The map is represented as a matrix of 0s and 1s, where 0s are passable space and 1s are impassable walls. The door out of the prison is at the top left (0,0) and the door into an escape pod is at the bottom right (w-1,h-1). 

Write a function answer(map) that generates the length of the shortest path from the prison door to the escape pod, where you are allowed to remove one wall as part of your remodeling plans. The path length is the total number of nodes you pass through, counting both the entrance and exit nodes. The starting and ending positions are always passable (0). The map will always be solvable, though you may or may not need to remove a wall. The height and width of the map can be from 2 to 20. Moves can only be made in cardinal directions; no diagonal moves are allowed.

Languages
=========

To provide a Python solution, edit solution.py
To provide a Java solution, edit solution.java

Test cases
==========

Inputs:
    (int) maze = [[0, 1, 1, 0], [0, 0, 0, 1], [1, 1, 0, 0], [1, 1, 1, 0]]
Output:
    (int) 7

Inputs:
    (int) maze = [[0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 0], [0, 0, 0, 0, 0, 0], [0, 1, 1, 1, 1, 1], [0, 1, 1, 1, 1, 1], [0, 0, 0, 0, 0, 0]]
Output:
    (int) 11

In [11]:
import numpy as np

In [12]:
test1 = np.array([[0, 1, 1, 0], [0, 0, 0, 1], [1, 1, 0, 0], [1, 1, 1, 0]])

In [13]:
test1

array([[0, 1, 1, 0],
       [0, 0, 0, 1],
       [1, 1, 0, 0],
       [1, 1, 1, 0]])

In [14]:
test2 = np.array([[0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 0], [0, 0, 0, 0, 0, 0], [0, 1, 1, 1, 1, 1], [0, 1, 1, 1, 1, 1], [0, 0, 0, 0, 0, 0]])

In [32]:
test2

array([[0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0]])

In [17]:
test0 = [[0,0],[0,0]]

In [33]:
steps = 0

i_loc = 0
j_loc = 0

wall_remove = False

loop_row = []
matrix = []

for i, row in enumerate(test1):

    for j, col in enumerate(row):
        
        print(j,col)


0 0
1 1
2 1
3 0
0 0
1 0
2 0
3 1
0 1
1 1
2 0
3 0
0 1
1 1
2 1
3 0


In [34]:
test1

array([[0, 1, 1, 0],
       [0, 0, 0, 1],
       [1, 1, 0, 0],
       [1, 1, 1, 0]])

In [36]:
len(test1[0])

4

In [195]:
# maze = [[0, 1, 1, 0], [0, 0, 0, 1], [1, 1, 0, 0], [1, 1, 1, 0]]
# maze = [[0,1,0],[0,1,0],[0,0,0]]
maze = test2

row_end = len(maze[0])
col_end = len(maze)

steps = 0

i = 0
j = 0

left_walk = True

wall_remove = False

loop_row = []
matrix = []

print(i,j, steps)

while i < row_end + 1 and j < col_end + 1:

    if j+1 < row_end and left_walk == True: #not sure if this needs to be j + 1 in col_end = len(maze), off by 1?
        
        if maze[i][j+1] == 0:
            j += 1
            steps += 1
            print('moved right')
            print(i,j,steps)
            
            
        elif maze[i][j+1] == 1:
            print('found wall to my right')
            pass
            
    elif i < col_end:

        if maze[i+1][j] == 0:
            i += 1
            steps += 1
            print('moved down')
            print(i,j,steps)
            left_walk = True
            
        elif maze[i+1][j] == 1:
            print('found wall below')
            left_walk = False
            j -= 2
            steps += 1
            print(i,j,steps)
            pass
    
#     if i+1 < col_end and j+1 < col_end and i > 0 and j > 0:
        
#         if maze[i][j+1] == 1 and maze[i+1][j] == 1:

#             i -= 2
#             steps += 1
            print('found corner')
                     
    if i == row_end-1 and j == col_end-1:
        
        print("Found Exit")
        print(i,j,steps)
        break
        
print("\nSolved maze in",steps, "steps")

0 0 0
moved right
0 1 1
moved right
0 2 2
moved right
0 3 3
moved right
0 4 4
moved right
0 5 5
moved down
1 5 6
moved down
2 5 7
found wall below
2 3 8
found corner
found wall below
2 1 9
found corner
found wall below
2 -1 10
found corner
found wall below
2 -3 11
found corner
found wall below
2 -5 12
found corner
found wall below
2 -7 13
found corner


IndexError: index -7 is out of bounds for axis 0 with size 6

In [104]:
i

2

In [115]:
col_end

6

In [42]:
try:
    sds
    print('foo')
except:
    print('bar')

bar


In [82]:
maze[0][1]

1

In [138]:
# maze = [[0, 1, 1, 0], [0, 0, 0, 1], [1, 1, 0, 0], [1, 1, 1, 0]]
# maze = [[0,1,0],[0,1,0],[0,0,0]]
maze = test2

row_end = len(maze[0])
col_end = len(maze)

steps = 0

i = 0
j = 0

left_walk = True

wall_remove = False

loop_row = []
matrix = []

print(i,j, steps)

while i < row_end and j < col_end:

    if j+1 < row_end and left_walk == True: #not sure if this needs to be j + 1 in col_end = len(maze), off by 1?
        
        if maze[i][j+1] == 0:
            j += 1
            steps += 1
            print('moved right')
            print(i,j,steps)
            continue  #this is a dank function.
            
            
        elif maze[i][j+1] == 1:
            print('found wall to my right')
            pass
            
    if i+1 < col_end:

        if maze[i+1][j] == 0:
            i += 1
            steps += 1
            print('moved down')
            print(i,j,steps)
            left_walk = True
            continue
            
        elif maze[i+1][j] == 1:
            print('found wall below')
            left_walk = False
            j -= 2
            steps += 1
            print(i,j,steps)
            pass
    
#     if i+1 < col_end and j+1 < col_end and i > 0 and j > 0:
        
#         if maze[i][j+1] == 1 and maze[i+1][j] == 1:

#             i -= 2
#             steps += 1
            print('found corner')
                     
    if i == row_end-1 and j == col_end-1:
        
        print("Found Exit")
        print(i,j,steps)
        break
        
print("\nSolved maze in",steps, "steps")

0 0 0
moved right
0 1 1
moved right
0 2 2
moved right
0 3 3
moved right
0 4 4
moved right
0 5 5
moved down
1 5 6
moved down
2 5 7
found wall below
2 3 8
found corner
found wall below
2 1 9
found corner
found wall below
2 -1 10
found corner
found wall below
2 -3 11
found corner
found wall below
2 -5 12
found corner
found wall below
2 -7 13
found corner


IndexError: index -7 is out of bounds for axis 0 with size 6

In [197]:
# maze = [[0, 1, 1, 0], [0, 0, 0, 1], [1, 1, 0, 0], [1, 1, 1, 0]]
# maze = [[0,1,0],[0,1,0],[0,0,0]]
maze = test2

row_end = len(maze[0]) - 1
col_end = len(maze) - 1

steps = 0

i = 0
j = 0

left_walk = False
wall_below = False
wall_left = False
wall_right = False

wall_remove = False

loop_row = []
matrix = []

print(i,j, steps)

while i <= row_end and j <= col_end:
    
#     print("j:",j,"j+1 = ", j+1)
    
    if j < row_end+1 and left_walk == False and wall_right == False:
        #not sure if this needs to be j + 1 in col_end = len(maze), off by 1?
        
        if j == row_end:
            print('found wall to my right (edge of maze)')
            left_walk = True
        
        elif maze[i][j+1] == 1:
            print('found wall to my right')
            left_walk = True
            wall_right = True
            pass
        
        elif maze[i][j+1] == 0:
            j += 1
            steps += 1
            print('moved right')
            print(i,j,steps)
            continue  #this is a dank function.
            
#     elif maze[i][j+1] == 1 and i < col_end+1:
    
    elif i < col_end+1 and wall_below == False:
        print('checking down')
        
        if i == col_end:
            print('found wall below (edge of maze)')
            wall_below = True
            
        elif maze[i+1][j] == 1:
            print('found wall below')
            wall_below = True
            pass
        
        elif maze[i+1][j] == 0:
            i += 1
            steps += 1
            print('moved down')
            print(i,j,steps)
            continue
        
#     if maze[i][j+1] == 1 and maze[i+1][j] == 1:
    
#         print('found corner')
#         left_walk = True
    
    elif left_walk == True and j-1 >= 0:
        print('checking left walk')
        if maze[i][j-1] == 0:
            j -= 1
            steps += 1
            print("moved left")
            print(i,j,steps)
            
        elif maze[i][j-1] == 1:
            print("found wall on my left")
            left_walk = False
            wall_left = True
            
            
    if i < col_end+1 and wall_below == True:
        
        if i == col_end:
            print('found bottom (edge of maze)')
            continue
            
        elif maze[i+1][j] == 0:
            wall_below = False
            print("turned off 'wall_below")
    
#     if j < row_end+1 and left_walk == True:
        
#         if j == row_end:
#             pass
        
#         elif maze[i][j+1] == 0:
#             print('Right is clear, switching direction')
#             left_walk = False
    
    if i == row_end-1 and j == col_end-1:
        
        print("Found Exit")
        print(i,j,steps)
        break
        
print("\nSolved maze in",steps, "steps")


## I should re-write this such that I can keep track of walls around me.

0 0 0
moved right
0 1 1
moved right
0 2 2
moved right
0 3 3
moved right
0 4 4
moved right
0 5 5
found wall to my right (edge of maze)
checking down
moved down
1 5 6
checking down
moved down
2 5 7
checking down
found wall below
checking left walk
moved left
2 4 8
checking left walk
moved left
2 3 9
checking left walk
moved left
2 2 10
checking left walk
moved left
2 1 11
checking left walk
moved left
2 0 12
turned off 'wall_below
checking down
moved down
3 0 13
checking down
moved down
4 0 14
checking down
moved down
5 0 15
checking down
found wall below (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found

found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge o

found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge o

found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge o

found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge o

found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge o

found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge o

found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge o

found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge of maze)
found bottom (edge o

KeyboardInterrupt: 

In [149]:
row_end

5

In [198]:
maze = [[0, 1, 1, 0], [0, 0, 0, 1], [1, 1, 0, 0], [1, 1, 1, 0]]
# maze = [[0,1,0],[0,1,0],[0,0,0]]
# maze = test2

row_end = len(maze[0]) - 1
col_end = len(maze) - 1

steps = 0

i = 0
j = 0

left_walk = False
wall_below = False
wall_left = False
wall_right = False

wall_remove = False

loop_row = []
matrix = []

print(i,j, steps)

while i <= row_end and j <= col_end:
    
#     print("j:",j,"j+1 = ", j+1)
    
    if j < row_end+1 and left_walk == False and wall_right == False:
        #not sure if this needs to be j + 1 in col_end = len(maze), off by 1?
        
        if j == row_end:
            print('found wall to my right (edge of maze)')
            wall_right = True
#             left_walk = True
        
        elif maze[i][j+1] == 1:
            print('found wall to my right')
#             left_walk = True
            wall_right = True
            pass
        
        elif maze[i][j+1] == 0:
            j += 1
            steps += 1
            print('moved right')
            print(i,j,steps)
            continue  #this is a dank function.

    
    elif i < col_end+1 and wall_below == False:
        print('checking down')
        
        if i == col_end:
            print('found wall below (edge of maze)')
            wall_below = True
            
        elif maze[i+1][j] == 1:
            print('found wall below')
            wall_below = True
            pass
        
        elif maze[i+1][j] == 0:
            i += 1
            steps += 1
            print('moved down')
            print(i,j,steps)
            continue
        
#     if maze[i][j+1] == 1 and maze[i+1][j] == 1:
    
#         print('found corner')
#         left_walk = True
    
    elif left_walk == True and j-1 >= 0:
        print('checking left walk')
        if maze[i][j-1] == 0:
            j -= 1
            steps += 1
            print("moved left")
            print(i,j,steps)
            
        elif maze[i][j-1] == 1:
            print("found wall on my left")
            left_walk = False
            wall_left = True
            
            
    if i < col_end+1 and wall_below == True:
        
        if i == col_end:
            print('found bottom (edge of maze)')
            continue
            
        elif maze[i+1][j] == 0:
            wall_below = False
            print("turned off 'wall_below")
    
#     if j < row_end+1 and left_walk == True:
        
#         if j == row_end:
#             pass
        
#         elif maze[i][j+1] == 0:
#             print('Right is clear, switching direction')
#             left_walk = False
    
    if i == row_end-1 and j == col_end-1:
        
        print("Found Exit")
        print(i,j,steps)
        break
        
        
    if j < row
        
print("\nSolved maze in",steps, "steps")


## I should re-write this such that I can keep track of walls around me.

0 0 0
found wall to my right
checking down
moved down
1 0 1
checking down
found wall below


KeyboardInterrupt: 

In [226]:
maze = [[0, 1, 1, 0], [0, 0, 0, 1], [1, 1, 0, 0], [1, 1, 1, 0]]


i = 0
j = 0

row_end = len(maze[0]) - 1
col_end = len(maze) - 1

# print("Maze Shape: " ,row_end,'rows and', col_end, "columns")
# print("start location:", i, j)

# print(np.array(maze))


right_wall = False
left_wall = False

bot_wall = False
top_wall = False

while i <= row_end and j <= col_end:
    
    # wall check and edge check:
    if i == 0:
#         print("At top of maze")
        top_wall = True
        
    if j == 0:
#         print("At left edge of maze")
        left_wall = True
        
    if i == col_end:
#         print("At bottom edge of maze")
        bot_wall = True
        
    if j == row_end:
#         print("At right edge of maze")
        right_wall = True
        
    if j+1 <= row_end:
        
        if maze[i][j+1] == 1:
#             print("Found wall to right")
            right_wall = True
    
    if j > 0:
        
        if maze[i][j-1] == 1:
#             print("Found wall to left")
            left_wall = True
            
    if i+1 <= col_end:
        
        if maze[i+1][j] == 1:
#             print("Found wall below")
            bot_wall = True
            
    if i > 0:
        
        if maze[i-1][j] == 1:
#             print("Found wall above")
            top_wall = True
        
    # Start movement steps:
    
    if j < row_end + 1 and right_wall == False:
        
#         print("moved right")
        j += 1
        steps += 1
        print(i,j,steps)
        
    if i < col_end + 1 and bot_wall == False:
        
#         print("moved down")
        i += 1
        steps += 1
        print(i,j,steps)
        
            
    right_wall = False
    left_wall = False

    bot_wall = False
    top_wall = False
    
    if i == col_end and j == row_end:
        
#         print('Solved Maze')
        break
    
#     break

Maze Shape:  3 rows and 3 columns
start location: 0 0
[[0 1 1 0]
 [0 0 0 1]
 [1 1 0 0]
 [1 1 1 0]]
At top of maze
At left edge of maze
Found wall to right
moved down
1 0 18
At left edge of maze
Found wall below
moved right
1 1 19
Found wall below
Found wall above
moved right
1 2 20
Found wall to right
Found wall above
moved down
2 2 21
Found wall to left
Found wall below
moved right
2 3 22
At right edge of maze
Found wall above
moved down
3 3 23
Solved Maze


In [290]:
# maze = [[0, 1, 1, 0], [0, 0, 0, 1], [1, 1, 0, 0], [1, 1, 1, 0]]

def answer(maze):
    i = 0
    j = 0
    steps = 0
    
    row_end = len(maze[0]) - 1
    col_end = len(maze) - 1

    print("Maze Shape: " ,row_end,'rows and', col_end, "columns")
    print("start location:", i, j)

    print(np.array(maze))


    right_wall = False
    left_wall = False

    bot_wall = False
    top_wall = False
    
    left_walk = False

    while i <= row_end and j <= col_end:

        print("Left Walk = ", left_walk)
            
        # wall check and edge check:
        if i == 0:
            print("At top of maze")
            top_wall = True

        if j == 0:
            print("At left edge of maze")
            left_wall = True

        if i == col_end:
            print("At bottom edge of maze")
            bot_wall = True

        if j == row_end:
            print("At right edge of maze")
            right_wall = True

        if j+1 <= row_end:

            if maze[i][j+1] == 1:
                print("Found wall to right")
                right_wall = True

        if j > 0:

            if maze[i][j-1] == 1:
                print("Found wall to left")
                left_wall = True

        if i+1 <= col_end:

            if maze[i+1][j] == 1:
                print("Found wall below")
                bot_wall = True

        if i > 0:

            if maze[i-1][j] == 1:
                print("Found wall above")
                top_wall = True

                
        if right_wall == True and bot_wall == True:
            
            left_walk = True
            
        if left_wall == True:
            
            left_walk == False
            
        if left_wall == True and right_wall == False and bot_wall == True:
            
            left_walk = False
            
        # Start movement steps:

        if j < row_end + 1 and right_wall == False and left_walk == False:

            print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved right")
            j += 1
            steps += 1
            print(i,j,steps)
            
        if j >= 0 and j - 1 >= 0 and left_walk == True:
            
            print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved left")
            j -= 1
            steps += 1
            print(i,j,steps)
            
        if i < col_end + 1 and bot_wall == False:

            print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved down")
            i += 1
            steps += 1
            print(i,j,steps)
            
            
#         if i < col_end


        right_wall = False
        left_wall = False

        bot_wall = False
        top_wall = False

        if i == col_end and j == row_end:

            print('Solved Maze')
            break

    return steps + 1
#     break

In [287]:
maze

[[0, 1, 1, 0], [0, 0, 0, 1], [1, 1, 0, 0], [1, 1, 1, 0]]

In [291]:
answer(maze)

Maze Shape:  3 rows and 3 columns
start location: 0 0
[[0 1 1 0]
 [0 0 0 1]
 [1 1 0 0]
 [1 1 1 0]]
Left Walk =  False
At top of maze
At left edge of maze
Found wall to right
>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved down
1 0 1
Left Walk =  False
At left edge of maze
Found wall below
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved right
1 1 2
Left Walk =  False
Found wall below
Found wall above
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved right
1 2 3
Left Walk =  False
Found wall to right
Found wall above
>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved down
2 2 4
Left Walk =  False
Found wall to left
Found wall below
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved right
2 3 5
Left Walk =  False
At right edge of maze
Found wall above
>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved down
3 3 6
Solved Maze


7

In [292]:
answer(test2)

Maze Shape:  5 rows and 5 columns
start location: 0 0
[[0 0 0 0 0 0]
 [1 1 1 1 1 0]
 [0 0 0 0 0 0]
 [0 1 1 1 1 1]
 [0 1 1 1 1 1]
 [0 0 0 0 0 0]]
Left Walk =  False
At top of maze
At left edge of maze
Found wall below
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved right
0 1 1
Left Walk =  False
At top of maze
Found wall below
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved right
0 2 2
Left Walk =  False
At top of maze
Found wall below
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved right
0 3 3
Left Walk =  False
At top of maze
Found wall below
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved right
0 4 4
Left Walk =  False
At top of maze
Found wall below
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved right
0 5 5
Left Walk =  False
At top of maze
At right edge of maze
>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved down
1 5 6
Left Walk =  False
At right edge of maze
Found wall to left
>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved down
2 5 7
Left Walk =  False
At right edge of maze
Found wall below
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved left
2 4 8
Left Walk =  True


21

In [307]:
# maze = [[0, 1, 1, 0], [0, 0, 0, 1], [1, 1, 0, 0], [1, 1, 1, 0]]

def answer(maze):
    i = 0
    j = 0
    steps = 0
    break_count = 0
    
    row_end = len(maze[0]) - 1
    col_end = len(maze) - 1

#     print("Maze Shape: " ,row_end,'rows and', col_end, "columns")
#     print("start location:", i, j)

#     print(np.array(maze))


    right_wall = False
    left_wall = False

    bot_wall = False
    top_wall = False
    
    left_walk = False
    up_walk = False

    while i <= row_end and j <= col_end and break_count < 1000:

#         print("Left Walk = ", left_walk)
        break_count += 1
        # wall check and edge check:
        if i == 0:
            print("At top of maze")
            top_wall = True

        if j == 0:
            print("At left edge of maze")
            left_wall = True

        if i == col_end:
            print("At bottom edge of maze")
            bot_wall = True

        if j == row_end:
            print("At right edge of maze")
            right_wall = True

        if j+1 <= row_end:

            if maze[i][j+1] == 1:
                print("Found wall to right")
                right_wall = True

        if j > 0:

            if maze[i][j-1] == 1:
                print("Found wall to left")
                left_wall = True

        if i+1 <= col_end:

            if maze[i+1][j] == 1:
                print("Found wall below")
                bot_wall = True

        if i > 0:

            if maze[i-1][j] == 1:
                print("Found wall above")
                top_wall = True

                
        if right_wall == True and bot_wall == True:
            
            left_walk = True
            
        if left_wall == True:
            
            left_walk == False
            
        if left_wall == True and right_wall == False and bot_wall == True:
            
            left_walk = False
            
            
        if bot_wall == True and left_wall == True:
            
            up_walk == True
        
        if top_wall == True:
            
            up_walk == False
            
        if bot_wall == False and top_wall == True and right_wall == True:
            
            up_walk == False
            
        # Start movement steps:

        if j < row_end + 1 and right_wall == False and left_walk == False:

            print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved right")
            j += 1
            steps += 1
#             print(i,j,steps)
            
        if j >= 0 and j - 1 >= 0 and left_walk == True:
            
            print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved left")
            j -= 1
            steps += 1
#             print(i,j,steps)
            
        if i < col_end + 1 and bot_wall == False:

            print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved down")
            i += 1
            steps += 1
            print(i,j,steps)
            
        if i >= 0 and i - 1 >= 0 and up_walk == True:
            
            print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved down")
            i -= 1
            steps += 1
            print(i,j,steps)
            
#         if i < col_end


        right_wall = False
        left_wall = False

        bot_wall = False
        top_wall = False

        if i == col_end and j == row_end:

            print('Solved Maze')
            break
    
    return steps + 1
#     break

In [317]:
answer(test2)

At top of maze
At left edge of maze
Found wall below
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved right
At top of maze
Found wall below
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved right
At top of maze
Found wall below
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved right
At top of maze
Found wall below
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved right
At top of maze
Found wall below
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved right
At top of maze
At right edge of maze
>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved down
1 5 6
At right edge of maze
Found wall to left
>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved down
2 5 7
At right edge of maze
Found wall below
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved left
Found wall below
Found wall above
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved left
Found wall below
Found wall above
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved left
Found wall below
Found wall above
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved left
Found wall below
Found wall above
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> moved left
At left edge of maze
Found wall above
>>>>>>>>>

21

In [318]:
## This is as far as I got, need to try looking in to Depth for Search.

In [298]:
test2.T

array([[0, 1, 0, 0, 0, 0],
       [0, 1, 0, 1, 1, 0],
       [0, 1, 0, 1, 1, 0],
       [0, 1, 0, 1, 1, 0],
       [0, 1, 0, 1, 1, 0],
       [0, 0, 0, 1, 1, 0]])

In [314]:
test1 = np.array([[0, 1, 1, 0], [0, 0, 0, 1], [1, 1, 0, 0], [1, 1, 1, 0]])

In [323]:
# Trying to make a node_tree to apply a DFS function:

node_tree = {}

row_end = len(maze[0]) - 1
col_end = len(maze)    - 1

for i_idx, i in enumerate(maze):
    layer = []
#     print(idx, i)
    
    for j_idx, j in enumerate(i):

        if i_idx <= col_end and j_idx <= row_end:
#             print(i_idx, j_idx)
            if maze[i_idx][j_idx] == 0 and i_idx + 1 <= col_end and j_idx + 1 <= col_end:
                
                if maze[i_idx][j_idx + 1] == 0 or maze[i_idx+1][j_idx] == 0:

                    layer.append([i_idx,j_idx])
                    
            if maze[i_idx][j_idx] == 0 and j_idx == row_end and i_idx + 1 <= col_end:
                
                if maze[i_idx][j_idx - 1] == 0 or maze[i_idx+1][j_idx] == 0:

                    layer.append([i_idx,j_idx])
                
            elif maze[i_idx][j_idx] == 0 and i_idx == col_end and j_idx + 1 <= row_end:
                
                if maze[i_idx][j_idx + 1] == 0 or maze[i_idx+1][j_idx] == 0:
                
                    layer.append([i_idx,j_idx])
                    
            elif maze[i_idx][j_idx] == 0 and i_idx == col_end and j_idx == row_end:
                
                layer.append([i_idx,j_idx])
             
    node_tree[i_idx] = layer

In [324]:
for num in range(0,len(node_tree)):
    print(node_tree[num])

[[0, 0]]
[[1, 0], [1, 1], [1, 2]]
[[2, 2], [2, 3]]
[[3, 3]]


In [333]:
for k, v in node_tree.items():
    print(v[0])

[0, 0]
[1, 0]
[2, 2]
[3, 3]


In [339]:
# Re-doing node_tree but only grabbing the values and placing them into a list.

nodes = []

row_end = len(maze[0]) - 1
col_end = len(maze)    - 1

for i_idx, i in enumerate(maze):
    layer = []
#     print(idx, i)
    
    for j_idx, j in enumerate(i):

        if i_idx <= col_end and j_idx <= row_end:
#             print(i_idx, j_idx)
            if maze[i_idx][j_idx] == 0 and i_idx + 1 <= col_end and j_idx + 1 <= col_end:
                
                if maze[i_idx][j_idx + 1] == 0 or maze[i_idx+1][j_idx] == 0:

                    nodes.append([i_idx,j_idx])
                    
            if maze[i_idx][j_idx] == 0 and j_idx == row_end and i_idx + 1 <= col_end:
                
                if maze[i_idx][j_idx - 1] == 0 or maze[i_idx+1][j_idx] == 0:

                    nodes.append([i_idx,j_idx])
                
            elif maze[i_idx][j_idx] == 0 and i_idx == col_end and j_idx + 1 <= row_end:
                
                if maze[i_idx][j_idx + 1] == 0 or maze[i_idx+1][j_idx] == 0:
                
                    nodes.append([i_idx,j_idx])
                    
            elif maze[i_idx][j_idx] == 0 and i_idx == col_end and j_idx == row_end:
                
                nodes.append([i_idx,j_idx])

In [340]:
nodes

[[0, 0], [1, 0], [1, 1], [1, 2], [2, 2], [2, 3], [3, 3]]

In [390]:
node_tree = {}



for idx, v in enumerate(nodes):
    
    sight = []
    
    if [v[0] + 1, v[1]] in nodes:
        
        sight.append( (v[0] + 1, v[1]) )
        
    if [v[0], v[1] + 1] in nodes:
        
        sight.append( (v[0], v[1] + 1) )
        
    if [v[0] - 1, v[1]] in nodes:
        
        sight.append( (v[0] - 1, v[1]) )
        
    if [v[0], v[1] - 1] in nodes:
        
        sight.append( (v[0], v[1] - 1) )
        
    node_tree[idx] = sight

In [391]:
for k,v in node_tree.items():
    print(k ,":", v)

0 : [(1, 0)]
1 : [(1, 1), (0, 0)]
2 : [(1, 2), (1, 0)]
3 : [(2, 2), (1, 1)]
4 : [(2, 3), (1, 2)]
5 : [(3, 3), (2, 2)]
6 : [(2, 3)]


In [377]:
node_tree

{0: [[1, 0]],
 1: [[1, 1], [0, 0]],
 2: [[1, 2], [1, 0]],
 3: [[2, 2], [1, 1]],
 4: [[2, 3], [1, 2]],
 5: [[3, 3], [2, 2]],
 6: [[2, 3]]}

In [421]:
node_tree = {}

for idx, v in enumerate(nodes):
    
    sight = []
    
    if [v[0] + 1, v[1]] in nodes:
        
        sight.append( nodes.index([v[0] + 1, v[1]]) )
        
    if [v[0], v[1] + 1] in nodes:
        
        sight.append( nodes.index([v[0], v[1] + 1]) )
        
    if [v[0] - 1, v[1]] in nodes:
        
        sight.append( nodes.index([v[0] - 1, v[1]]) )
        
    if [v[0], v[1] - 1] in nodes:
        
        sight.append( nodes.index([v[0], v[1] - 1]) )
        
    node_tree[idx] = set(sight)
    

In [422]:
node_tree

{0: {1}, 1: {0, 2}, 2: {1, 3}, 3: {2, 4}, 4: {3, 5}, 5: {4, 6}, 6: {5}}

In [423]:
for k,v in node_tree.items():
    print(k ,":", v)

0 : {1}
1 : {0, 2}
2 : {1, 3}
3 : {2, 4}
4 : {3, 5}
5 : {4, 6}
6 : {5}


In [413]:
nodes

[[0, 0], [1, 0], [1, 1], [1, 2], [2, 2], [2, 3], [3, 3]]

In [414]:
nodes.index([2,3])

5

In [415]:
sorted(nodes)

[[0, 0], [1, 0], [1, 1], [1, 2], [2, 2], [2, 3], [3, 3]]

In [424]:
def bfs(graph, start):
    visited, queue = set(), [start]
    while queue:
        vertex = queue.pop(0)
        if vertex not in visited:
            visited.add(vertex)
            queue.extend(graph[vertex] - visited)
    return visited

In [425]:
bfs(node_tree, 0)

{0, 1, 2, 3, 4, 5, 6}

In [457]:
# Test answer, basic:

def answer(maze):
    print(np.array(maze))
    nodes = []

    row_end = len(maze[0]) - 1
    col_end = len(maze)    - 1

    for i_idx, i in enumerate(maze):
        layer = []
    #     print(idx, i)

        for j_idx, j in enumerate(i):

            if i_idx <= col_end and j_idx <= row_end:
    #             print(i_idx, j_idx)
                if maze[i_idx][j_idx] == 0 and i_idx + 1 <= col_end and j_idx + 1 <= col_end:

                    if maze[i_idx][j_idx + 1] == 0 or maze[i_idx+1][j_idx] == 0:

                        nodes.append([i_idx,j_idx])

                if maze[i_idx][j_idx] == 0 and j_idx == row_end and i_idx + 1 <= col_end:

                    if maze[i_idx][j_idx - 1] == 0 or maze[i_idx+1][j_idx] == 0:

                        nodes.append([i_idx,j_idx])

                elif maze[i_idx][j_idx] == 0 and i_idx == col_end and j_idx + 1 <= row_end:

                    if maze[i_idx][j_idx + 1] == 0 or maze[i_idx+1][j_idx] == 0:

                        nodes.append([i_idx,j_idx])

                elif maze[i_idx][j_idx] == 0 and i_idx == col_end and j_idx == row_end:

                    nodes.append([i_idx,j_idx])

    node_tree = {}

    for idx, v in enumerate(nodes):

        sight = []

        if [v[0] + 1, v[1]] in nodes:

            sight.append( nodes.index([v[0] + 1, v[1]]) )

        if [v[0], v[1] + 1] in nodes:

            sight.append( nodes.index([v[0], v[1] + 1]) )

        if [v[0] - 1, v[1]] in nodes:

            sight.append( nodes.index([v[0] - 1, v[1]]) )

        if [v[0], v[1] - 1] in nodes:

            sight.append( nodes.index([v[0], v[1] - 1]) )

        node_tree[idx] = set(sight)
        
    result = bfs(node_tree,0)
    print(len(result))
#     print(node_tree)
    return result

In [447]:
np.array(maze)

array([[0, 1, 1, 0],
       [0, 0, 0, 1],
       [1, 1, 0, 0],
       [1, 1, 1, 0]])

In [448]:
answer(maze)

[[0 1 1 0]
 [0 0 0 1]
 [1 1 0 0]
 [1 1 1 0]]
7


{0, 1, 2, 3, 4, 5, 6}

In [455]:
answer(test0)

[[0 0]
 [0 0]]
4
{0: {1, 2}, 1: {0, 3}, 2: {0, 3}, 3: {1, 2}}


{0, 1, 2, 3}

In [458]:
answer(test2)

[[0 0 0 0 0 0]
 [1 1 1 1 1 0]
 [0 0 0 0 0 0]
 [0 1 1 1 1 1]
 [0 1 1 1 1 1]
 [0 0 0 0 0 0]]
21


{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}