Minion Labor Shifts
===================

Commander Lambda's minions are upset! They're given the worst jobs on the whole space station, and some of them are starting to complain that even those worst jobs are being allocated unfairly. If you can fix this problem, it'll prove your chops to Commander Lambda so you can get promoted!

Minions' tasks are assigned by putting their ID numbers into a list, one time for each day they'll work that task. As shifts are planned well in advance, the lists for each task will contain up to 99 integers. When a minion is scheduled for the same task too many times, they'll complain about it until they're taken off the task completely. Some tasks are worse than others, so the number of scheduled assignments before a minion will refuse to do a task varies depending on the task.  You figure you can speed things up by automating the removal of the minions who have been assigned a task too many times before they even get a chance to start complaining.

Write a function called answer(data, n) that takes in a list of less than 100 integers and a number n, and returns that same list but with all of the numbers that occur more than n times removed entirely. The returned list should retain the same ordering as the original list - you don't want to mix up those carefully-planned shift rotations! For instance, if data was [5, 10, 15, 10, 7] and n was 1, answer(data, n) would return the list [5, 15, 7] because 10 occurs twice, and thus was removed from the list entirely.

Languages
=========

To provide a Python solution, edit solution.py
To provide a Java solution, edit solution.java

Test cases
==========

Inputs:
    (int list) data = [1, 2, 3]
    (int) n = 0
Output:
    (int list) []

Inputs:
    (int list) data = [1, 2, 2, 3, 3, 3, 4, 5, 5]
    (int) n = 1
Output:
    (int list) [1, 4]

Inputs:
    (int list) data = [1, 2, 3]
    (int) n = 6
Output:
    (int list) [1, 2, 3]

Use verify [file] to test your solution and see how it does. When you are finished editing your code, use submit [file] to submit your answer. If your solution passes the test cases, it will be removed from your home folder.

In [48]:
import random
import numpy as np
my_randoms = random.sample(list(np.arange(1,20,1)), 10)

In [61]:
new_test = []
for i in range(0,99):
    new_test.append(random.choice(np.arange(1,20,1)))

In [63]:
Counter(new_test)

Counter({1: 3,
         2: 5,
         3: 5,
         4: 8,
         5: 7,
         6: 6,
         7: 6,
         8: 7,
         9: 2,
         10: 4,
         11: 3,
         12: 9,
         13: 4,
         14: 5,
         15: 5,
         16: 6,
         17: 5,
         18: 2,
         19: 7})

In [73]:
Counter(rand_test2)

Counter({1: 9,
         2: 4,
         3: 4,
         4: 3,
         5: 2,
         6: 7,
         7: 4,
         8: 5,
         9: 8,
         10: 4,
         11: 4,
         12: 5,
         13: 4,
         14: 7,
         15: 6,
         16: 4,
         17: 8,
         18: 8,
         19: 3})

In [74]:
answer(rand_test1, 1)

[5]

In [3]:
test1 = [1,2,3]  # n = 0 -> []
test2 = [1,2,2,3,3,3,4,5,5]  # n = 1 -> [1,4]
test3 = [1,2,3]  # n = 6 -> [1,2,3]

# ID numbers that occur more times than n will be removed.

n = 1
# for item in test2:
    

In [6]:
from collections import Counter

Counter(test2)[2]

2

In [22]:
n = 1
result = []
for item in test2:
    print(n, item)
    if Counter(test2)[item] <= n:
        result.append(item)
        print(item)
    
result

1 1
1
1 2
1 2
1 3
1 3
1 3
1 4
4
1 5
1 5


[1, 4]

In [18]:
Counter(test2)[2] <= 6

True

In [23]:
def answer(data,n):
    result = []
    
    id_count = Counter(data)
    
    for minion_id in data:
        
        if id_count[minion_id] <= n:
            
            result.append(minion_id)
            
    return result

In [25]:
print(answer(test1,0))

[]


In [26]:
print(answer(test2,1))

[1, 4]


In [27]:
print(answer(test3,6))

[1, 2, 3]


In [145]:
# My solution:

def answer(data,n):
    
    if len(data) < 100:
    
        from collections import Counter  # Using Python's "Counter" function to count minion ID's as a dictionary.

        result = []

        id_count = Counter(data)   # Create dictionary to count frequency of all minion ID's in given list.

        for minion_id in data:

            if id_count[minion_id] <= n:  # Check if each ID count is less than defined n.

                result.append(minion_id)

        return result
    
    else:
        return "Error: Please enter list of less than 100 entries (up to 99)."

    
# # Test Cases:   

# test1 = [1,2,3]  # n = 0 -> []
# test2 = [1,2,2,3,3,3,4,5,5]  # n = 1 -> [1,4]
# test3 = [1,2,3]  # n = 6 -> [1,2,3]

# print("Test Cases:")
# print(answer(test1,0))
# print(answer(test2,1))
# print(answer(test3,6), "\n")

# # Random Test Cases:

# import random
# import numpy as np

# random.seed(1)

# rand_test1 = [random.choice(np.arange(1,21,1)) for i in range(0,50)]
# rand_test2 = [random.choice(np.arange(1,21,1)) for i in range(0,50)]
# rand_test3 = [random.choice(np.arange(1,21,1)) for i in range(0,50)]

# print("Random Test Cases: \n")
# N = 2  # Testing for n = 2
# for test_num, test in enumerate([rand_test1, rand_test2, rand_test3]):
    
#     print("Random Test #", str(test_num), ", n=N,", test, "\n")
#     print("ID's returned: ", answer(test,n = N), "\n")
#     print("Frequency of approved minions: ", [(k,v) for k, v in Counter(test).items() if v <= N])
#     print('\n')

Random Test Cases: 

Random Test # 0 , n=N, [5, 19, 3, 9, 4, 16, 15, 16, 13, 7, 4, 16, 1, 13, 14, 20, 1, 15, 9, 8, 19, 4, 11, 1, 1, 1, 18, 1, 13, 7, 14, 1, 17, 8, 15, 16, 18, 8, 12, 8, 8, 15, 10, 1, 14, 18, 4, 6, 10, 4] 

ID's returned:  [5, 19, 3, 9, 7, 20, 9, 19, 11, 7, 17, 12, 10, 6, 10] 

Frequency of approved minions:  [(5, 1), (19, 2), (3, 1), (9, 2), (7, 2), (20, 1), (11, 1), (17, 1), (12, 1), (10, 2), (6, 1)]


Random Test # 1 , n=N, [11, 17, 14, 17, 7, 10, 10, 19, 16, 17, 13, 19, 2, 16, 8, 13, 14, 6, 12, 18, 12, 3, 15, 17, 4, 6, 17, 13, 12, 16, 1, 16, 2, 10, 20, 19, 19, 13, 6, 6, 17, 8, 1, 7, 18, 18, 8, 13, 17, 12] 

ID's returned:  [11, 14, 7, 2, 14, 3, 15, 4, 1, 2, 20, 1, 7] 

Frequency of approved minions:  [(11, 1), (14, 2), (7, 2), (2, 2), (3, 1), (15, 1), (4, 1), (1, 2), (20, 1)]


Random Test # 2 , n=N, [19, 12, 15, 9, 18, 20, 1, 13, 17, 5, 17, 18, 7, 14, 2, 16, 12, 19, 18, 7, 17, 14, 16, 12, 14, 12, 1, 18, 18, 20, 20, 11, 15, 20, 1, 8, 6, 18, 19, 6, 3, 18, 9, 2, 3, 3, 

In [94]:
random.seed(1)

rand_test1 = [random.choice(np.arange(1,21,1)) for i in range(0,50)]

rand_test2 = [random.choice(np.arange(1,21,1)) for i in range(0,50)]

rand_test3 = [random.choice(np.arange(1,21,1)) for i in range(0,50)]

In [95]:
Counter(rand_test1)

Counter({1: 8,
         3: 1,
         4: 5,
         5: 1,
         6: 1,
         7: 2,
         8: 5,
         9: 2,
         10: 2,
         11: 1,
         12: 1,
         13: 3,
         14: 3,
         15: 4,
         16: 4,
         17: 1,
         18: 3,
         19: 2,
         20: 1})

In [115]:
print(answer(rand_test1,3))

[5, 19, 3, 9, 13, 7, 13, 14, 20, 9, 19, 11, 18, 13, 7, 14, 17, 18, 12, 10, 14, 18, 6, 10]


In [118]:
print([(k,v) for k, v in Counter(rand_test1).items() if v <= 3])

[(5, 1), (19, 2), (3, 1), (9, 2), (13, 3), (7, 2), (14, 3), (20, 1), (11, 1), (18, 3), (17, 1), (12, 1), (10, 2), (6, 1)]


In [114]:
for k, v in Counter(rand_test1).items():
    if v <= 3:
        print(k, v)

5 1
19 2
3 1
9 2
13 3
7 2
14 3
20 1
11 1
18 3
17 1
12 1
10 2
6 1


In [143]:
## Submitted solution:
# My solution:

# My solution:

def answer(data,n):
    
    if len(data) < 100:
    
        from collections import Counter  # Using Python's "Counter" function to count minion ID's as a dictionary.

        result = []

        id_count = Counter(data)   # Create dictionary to count frequency of all minion ID's in given list.

        for minion_id in data:

            if id_count[minion_id] <= n:  # Check if each ID count is less than defined n.

                result.append(minion_id)

        return result
    
    else:
        return "Error: Please enter list of less than 100 entries (up to 99)."

    
# # Test Cases:   

# test1 = [1,2,3]  # n = 0 -> []
# test2 = [1,2,2,3,3,3,4,5,5]  # n = 1 -> [1,4]
# test3 = [1,2,3]  # n = 6 -> [1,2,3]

# print("Test Cases:")
# print(answer(test1,0))
# print(answer(test2,1))
# print(answer(test3,6), "\n")

# print(answer([random.choice(np.arange(1,21,1)) for i in range(0,100)], 3))

# # Random Test Cases:

# import random
# import numpy as np

# random.seed(1)

# rand_test1 = [random.choice(np.arange(1,21,1)) for i in range(0,50)]
# rand_test2 = [random.choice(np.arange(1,21,1)) for i in range(0,50)]
# rand_test3 = [random.choice(np.arange(1,21,1)) for i in range(0,50)]

# print("Random Test Cases: \n")
# N = 2  # Testing for n = 2
# for test_num, test in enumerate([rand_test1, rand_test2, rand_test3]):
    
#     print("Random Test #", str(test_num), ", n=N,", test, "\n")
#     print("ID's returned: ", answer(test,n = N), "\n")
#     print("Frequency of approved minions: ", [(k,v) for k, v in Counter(test).items() if v <= N])
#     print('\n')

In [147]:
answer([random.choice(np.arange(1,21,1)) for i in range(0,100)], 3)

'Error: Please enter list of less than 100 entries (up to 99).'

## Level 2

En Route Salute
===============

Commander Lambda loves efficiency and hates anything that wastes time. She's a busy lamb, after all! She generously rewards henchmen who identify sources of inefficiency and come up with ways to remove them. You've spotted one such source, and you think solving it will help you build the reputation you need to get promoted.

Every time the Commander's employees pass each other in the hall, each of them must stop and salute each other - one at a time - before resuming their path. A salute is five seconds long, so each exchange of salutes takes a full ten seconds (Commander Lambda's salute is a bit, er, involved). You think that by removing the salute requirement, you could save several collective hours of employee time per day. But first, you need to show her how bad the problem really is.

Write a program that counts how many salutes are exchanged during a typical walk along a hallway. The hall is represented by a string. For example:
"--->-><-><-->-"

Each hallway string will contain three different types of characters: '>', an employee walking to the right; '<', an employee walking to the left; and '-', an empty space. Every employee walks at the same speed either to right or to the left, according to their direction. Whenever two employees cross, each of them salutes the other. They then continue walking until they reach the end, finally leaving the hallway. In the above example, they salute 10 times.

Write a function answer(s) which takes a string representing employees walking along a hallway and returns the number of times the employees will salute. s will contain at least 1 and at most 100 characters, each one of -, >, or <.

Languages
=========

To provide a Python solution, edit solution.py
To provide a Java solution, edit solution.java

Test cases
==========

Inputs:
    (string) s = ">----<"
Output:
    (int) 2

Inputs:
    (string) s = "<<>><"
Output:
    (int) 4

Use verify [file] to test your solution and see how it does. When you are finished editing your code, use submit [file] to submit your answer. If your solution passes the test cases, it will be removed from your home folder.

Java
====

Your code will be compiled using standard Java 8. It must implement the answer() method in the solution stub.

Execution time is limited. Some classes are restricted (e.g. java.lang.ClassLoader). You will see a notice if you use a restricted class when you verify your solution.

Third-party libraries, input/output operations, spawning threads or processes and changes to the execution environment are not allowed.

Python
======

Your code will run inside a Python 2.7.6 sandbox.

Standard libraries are supported except for bz2, crypt, fcntl, mmap, pwd, pyexpat, select, signal, termios, thread, time, unicodedata, zipimport, zlib.

In [149]:
test1 = "--->-><-><-->-"  # 10 salutes
test2 = ">----<"   # 2 salutes
test3 = "<<>><" # 4 salutes

In [235]:
s = test1

total_right_salutes = 0
for idx, char in enumerate(s):
    if char == ">":
        
        loop_salutes = 0
        
        sight = ''.join([str(direction) for direction in s[idx+1:]])  #checking sight of right-facing guard.
        print(sight)
        
        for target in sight:
            if target == "<":
                loop_salutes += 1
        
        total_right_salutes += loop_salutes
        print(loop_salutes, total_right_salutes)
        


-><-><-->-
2 2
<-><-->-
2 4
<-->-
1 5
-
0 5


In [224]:
test1

'--->-><-><-->-'

In [239]:
s = test1

def SaluteCounter(s):
    
    total_right_salutes = 0
    
    for idx, char in enumerate(s):
        # First checking right-facing guards.
        if char == ">":

            right_salutes = 0

            sight = ''.join([str(direction) for direction in s[idx+1:]])  #checking sight of right-facing guard.
            print(sight)

            for target in sight:
                if target == "<":
                    right_salutes += 1

            total_right_salutes += right_salutes
            print(right_salutes, total_right_salutes)
            
    return total_right_salutes
            
SaluteCounter(s)

# Second, flipping hallway and checking left-facing guards (which are now in the reverse direction)
reversed_s = ""
    
for char in s[::-1]:
    if char == "-":
        reversed_s += "-"
    elif char == ">":
        reversed_s += "<"
    elif char == "<":
        reversed_s += ">"

print("frontwards:", s)
print("reversed:  ", reversed_s)

SaluteCounter(reversed_s)

print(SaluteCounter(s) + SaluteCounter(reversed_s))

-><-><-->-
2 2
<-><-->-
2 4
<-->-
1 5
-
0 5
frontwards: --->-><-><-->-
reversed:   -<--><-><-<---
<-><-<---
3 3
<-<---
2 5
-><-><-->-
2 2
<-><-->-
2 4
<-->-
1 5
-
0 5
<-><-<---
3 3
<-<---
2 5
10


In [242]:
s = test1

def SaluteCounter(s):
    
    total_right_salutes = 0
    
    for idx, char in enumerate(s):
        # First checking right-facing guards.
        if char == ">":

            right_salutes = 0

            sight = ''.join([str(direction) for direction in s[idx+1:]])  #checking sight of right-facing guard.
            print(sight)

            for target in sight:
                if target == "<":
                    right_salutes += 1

            total_right_salutes += right_salutes
            print(right_salutes, total_right_salutes)
            
    return total_right_salutes
            
SaluteCounter(s)

# Second, flipping hallway and checking left-facing guards (which are now in the reverse direction)
reversed_s = ""
    
for char in s[::-1]:
    if char == "-":
        reversed_s += "-"
    elif char == ">":
        reversed_s += "<"
    elif char == "<":
        reversed_s += ">"

print("frontwards:", s)
print("reversed:  ", reversed_s)

SaluteCounter(reversed_s)

print(SaluteCounter(s) + SaluteCounter(reversed_s))

-><-><-->-
2 2
<-><-->-
2 4
<-->-
1 5
-
0 5
frontwards: --->-><-><-->-
reversed:   -<--><-><-<---
<-><-<---
3 3
<-<---
2 5
-><-><-->-
2 2
<-><-->-
2 4
<-->-
1 5
-
0 5
<-><-<---
3 3
<-<---
2 5
10


In [266]:
## My solution Submission Draft
def answer(s):

    def SaluteCounter(s):
        
    # This function counts up all of the salutes in one direction (facing right)
    # This will be used twice, once on the original list for "right facing" salutes, and
    # again for "left facing salutes" after the string has been flipped (preserving direction of guards.
    
        total_right_salutes = 0

        for idx, char in enumerate(s):
            # Checking right-facing guards.
            if char == ">":

                right_salutes = 0

                sight = ''.join([str(direction) for direction in s[idx+1:]])  # Checking sight of right-facing guard.
#                 print(sight)

                for target in sight:
                    if target == "<":
                        right_salutes += 1  # Counting each opposite facing guard in line of sight.

                total_right_salutes += right_salutes
#                 print(right_salutes, total_right_salutes)

        return total_right_salutes

    # Flipping hallway (which are now in the reverse direction) to check salutes of left-facing guards.
    reversed_s = ""

    for char in s[::-1]:
        if char == "-":
            reversed_s += "-"
        elif char == ">":
            reversed_s += "<"
        elif char == "<":
            reversed_s += ">"

#     print("frontwards:", s)
#     print("reversed:  ", reversed_s)
    
    #Answer will be calculated using SaluteCounter for the original string and the "reversed" string.
    return (SaluteCounter(s) + SaluteCounter(reversed_s))

In [281]:
# # Test Cases

# test1 = "--->-><-><-->-"  # 10 salutes
# test2 = ">----<"   # 2 salutes
# test3 = "<<>><" # 4 salutes

# print(test1, "\n", answer(test1), "salutes,", str(answer(test1)*5), "seconds spent saluting.\n")
# print(test2, "\n", answer(test2), "salutes,", str(answer(test2)*5), "seconds spent saluting.\n")
# print(test3, "\n", answer(test3), "salutes,", str(answer(test3)*5), "seconds spent saluting.\n")

--->-><-><-->- 
 10 salutes, 50 seconds spent saluting.

>----< 
 2 salutes, 10 seconds spent saluting.

<<>>< 
 4 salutes, 20 seconds spent saluting.



In [354]:
# # Random Test Cases

# import random
# import numpy as np

# np.random.seed(1)

# rand_test1 = ''.join(np.random.choice(['>', '<', '-'],30, p = [0.1,0.1,0.8]))

# print(rand_test1, "\n", answer(rand_test1), "salutes,", str(answer(rand_test1)*5), "seconds spent saluting.\n")


# rand_test2 = ''.join(np.random.choice(['>', '<', '-'],40, p = [0.1,0.1,0.8]))

# print(rand_test2, "\n", answer(rand_test2), "salutes,", str(answer(rand_test2)*5), "seconds spent saluting.\n")

# rand_test3 = ''.join(np.random.choice(['>', '<', '-'],50, p = [0.2,0.2,0.6]))

# print(rand_test3, "\n", answer(rand_test3), "salutes,", str(answer(rand_test3)*5), "seconds spent saluting.\n")

-->-<><------->---<<------>><- 
 28 salutes, 140 seconds spent saluting.

>------->-----<----<>---->-<--<--->----- 
 24 salutes, 120 seconds spent saluting.

->>-<>-<-----<<----->----<-->-<--<-->--->>-->----> 
 50 salutes, 250 seconds spent saluting.



In [267]:
answer(test1)

10

In [268]:
answer(test2)

2

In [269]:
answer(test3)

4

Bunny Prisoner Locating
=======================

Keeping track of Commander Lambda's many bunny prisoners is starting to get tricky. You've been tasked with writing a program to match bunny prisoner IDs to cell locations.

The LAMBCHOP doomsday device takes up much of the interior of Commander Lambda's space station, and as a result the prison blocks have an unusual layout. They are stacked in a triangular shape, and the bunny prisoners are given numerical IDs starting from the corner, as follows:

| 7

| 4 8

| 2 5 9

| 1 3 6 10

Each cell can be represented as points (x, y), with x being the distance from the vertical wall, and y being the height from the ground. 

For example, the bunny prisoner at (1, 1) has ID 1, the bunny prisoner at (3, 2) has ID 9, and the bunny prisoner at (2,3) has ID 8. This pattern of numbering continues indefinitely (Commander Lambda has been taking a LOT of prisoners). 

Write a function answer(x, y) which returns the prisoner ID of the bunny at location (x, y). Each value of x and y will be at least 1 and no greater than 100,000. Since the prisoner ID can be very large, return your answer as a string representation of the number.

Languages
=========

To provide a Python solution, edit solution.py
To provide a Java solution, edit solution.java

Test cases
==========

Inputs:
    (int) x = 3
    (int) y = 2
Output:
    (string) "9"

Inputs:
    (int) x = 5
    (int) y = 10
Output:
    (string) "96"


In [410]:
test_matrix = [[1,3,6,10], [2,5,9,0], [4, 8, 0 , 0], [7, 0, 0, 0]]

In [411]:
np.array(test_matrix)

array([[ 1,  3,  6, 10],
       [ 2,  5,  9,  0],
       [ 4,  8,  0,  0],
       [ 7,  0,  0,  0]])

In [412]:
np.array(test_matrix)[0,0]

1

In [417]:
np.array(test_matrix)[2,2]

0

In [416]:
np.array(test_matrix)[1,2]

9

In [386]:
test_matrix_bars = [['-','-','-','-','-'],["|",1,3,6,10], ['|',2,5,9,0], ['|',4, 8, 0 , 0], ['|',7, 0, 0, 0]]

In [448]:
np.array(test_matrix_bars)[::-1]

array([['|', '7', '0', '0', '0'],
       ['|', '4', '8', '0', '0'],
       ['|', '2', '5', '9', '0'],
       ['|', '1', '3', '6', '10'],
       ['-', '-', '-', '-', '-']], dtype='<U2')

In [426]:
np.array(test_matrix_bars)[3,2]

'8'

In [427]:
np.array(test_matrix_bars)[2,3]

'9'

In [ ]:
np.array(test_matrix_bars)[2,3]

In [434]:
def answer(x, y):
    prison = [['-','-','-','-','-'],["|",1,3,6,10], ['|',2,5,9,0], ['|',4, 8, 0 , 0], ['|',7, 0, 0, 0]]
    prison_matrix = np.array(prison)
    return prison_matrix[x+1,y+1]

In [463]:
def answer(x, y):
    
    import numpy as np
    
    prison = [[1,3,6,10], [2,5,9,0], [4, 8, 0 , 0], [7, 0, 0, 0]]
    prison_matrix = np.array(prison)
    
    return str(prison_matrix[y-1,x-1])

In [460]:
answer(x = 2, y = 3)

'8'

In [461]:
answer(x = 3, y = 2)

'9'

In [462]:
answer(x = 1, y = 1)

'1'

In [493]:
np.arange(1,101).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [500]:
np.diag(np.arange(1,101)).reshape((100,100))

array([[  1,   0,   0, ...,   0,   0,   0],
       [  0,   2,   0, ...,   0,   0,   0],
       [  0,   0,   3, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,  98,   0,   0],
       [  0,   0,   0, ...,   0,  99,   0],
       [  0,   0,   0, ...,   0,   0, 100]])

In [505]:
np.diag([4,5,6])

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [482]:
100*1000

100000

In [513]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [516]:
np.arange(2,11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [515]:
np.arange(1,10) + np.arange(2,11)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [520]:
np.array([1,3,3,4,5,6]) + np.array([2,3,4,5,6,7])

array([ 3,  5,  7,  9, 11, 13])

In [531]:
cell = []
counter1 = 0
counter2 = 1

for i in np.array([1,2,3,4,5]):
    for j in np.array([2,3,4,5,6]):
    
        cell.append(i+counter1+counter2)
    
cell

[2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6]

In [ ]:
np.array([1,2,3,4,5]) +

In [680]:
cell = []
counter = 1

for i in np.array(np.arange(0,11)):
    cell.append(i + counter)
    counter += i + 1
    
cell

[1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 66]

In [701]:
np.arange(0,11)+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [702]:
cell = []
counter = 1

for i in np.arange(0,11)+2:
    cell.append(i + counter)
    counter += i + 1
    
cell

[3, 7, 12, 18, 25, 33, 42, 52, 63, 75, 88]

In [678]:
cell = []
counter = 1

for i in np.arange(0,11)+2:
    cell.append(i+counter)
    counter += i + 1
    
np.array(cell)

array([ 4,  9, 15, 22, 30, 39, 49, 60, 72, 85, 99])

In [679]:
cell = []
counter = 1

for i in np.array(np.arange(0,11))+6:
    cell.append(i+counter)
    counter += i + 1
    
cell

[7, 15, 24, 34, 45, 57, 70, 84, 99, 115, 132]

In [566]:
cell = []
counter = 1

for i in np.array(np.arange(0,11))+10:
    cell.append(i+counter)
    counter += i + 1
    
cell

[11, 23, 36, 50, 65, 81, 98, 116, 135, 155, 176]

In [574]:
1000*1000

1000000

In [590]:
####### important #######
multiplier = []
counter = 1

for i in np.array(np.arange(-1,1001)):
    multiplier.append(i+counter)
    counter += i + 1
    
print(multiplier[:20])

[0, 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 66, 78, 91, 105, 120, 136, 153, 171, 190]


In [646]:
####### important #######
for m in multiplier[0:8]:
    cell = []
    counter = 1
    for i in (np.arange(0,8))+m:
        cell.append(i+counter)
        counter += i + 1
    
    print(m, cell[:20])

0 [1, 3, 6, 10, 15, 21, 28, 36]
1 [2, 5, 9, 14, 20, 27, 35, 44]
3 [4, 9, 15, 22, 30, 39, 49, 60]
6 [7, 15, 24, 34, 45, 57, 70, 84]
10 [11, 23, 36, 50, 65, 81, 98, 116]
15 [16, 33, 51, 70, 90, 111, 133, 156]
21 [22, 45, 69, 94, 120, 147, 175, 204]
28 [29, 59, 90, 122, 155, 189, 224, 260]


In [629]:
test_matrix

array([[100., 100., 100., 100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100., 100., 100., 100.]])

In [619]:
prison_matrix

array([list([1, 3, 6, 10, 15]), list([2, 5, 9, 0]), list([4, 8, 0, 0]),
       list([7, 0, 0, 0])], dtype=object)

In [719]:

counter = 1
starter = np.arange(0,11)

for i in range(5):
    cell = []
    for idx, val in enumerate(starter):

        cell.append(idx + counter)

        counter+= idx + 1

    print(cell)
    starter += 1

[1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 66]
[67, 69, 72, 76, 81, 87, 94, 102, 111, 121, 132]
[133, 135, 138, 142, 147, 153, 160, 168, 177, 187, 198]
[199, 201, 204, 208, 213, 219, 226, 234, 243, 253, 264]
[265, 267, 270, 274, 279, 285, 292, 300, 309, 319, 330]


In [738]:
cell = []
counter = 1
starter = np.arange(0,11)

for i in starter:
    cell.append(i + counter)
    counter += i + 1
    
cell

[1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 66]

In [740]:
cell + starter+2

array([ 3,  6, 10, 15, 21, 28, 36, 45, 55, 66, 78])

In [735]:
starter+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [737]:
starter+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [785]:
##### First col #####
num = 1
col = []
for i in range(0,11):
    col.append(i + num)
    num = i + num
    
np.array(col).reshape(11,1)

array([[ 1],
       [ 2],
       [ 4],
       [ 7],
       [11],
       [16],
       [22],
       [29],
       [37],
       [46],
       [56]])

In [786]:
col

[1, 2, 4, 7, 11, 16, 22, 29, 37, 46, 56]

In [827]:
col2 = []
for idx, val in enumerate(np.array(col)):
#     print(idx, val, np.array([2,3,4,5,6,7,8,9])[idx])
#     print(val + np.array([2,3,4,5,6,7,8,9,10,11,12,13])[idx])
    col2.append(val + np.array([2,3,4,5,6,7,8,9,10,11,12,13])[idx])

In [831]:
col3 = []
for idx, val in enumerate(np.array(col2)):
#     print(idx, val, np.array([2,3,4,5,6,7,8,9])[idx])
#     print(val + np.array([2,3,4,5,6,7,8,9,10,11,12,13])[idx])
    col3.append(val + np.array([3,4,5,6,7,8,9,10,11,12,13])[idx])
col3

[6, 9, 13, 18, 24, 31, 39, 48, 58, 69, 81]

In [832]:
np.array([col,col2,col3]).T

array([[ 1,  3,  6],
       [ 2,  5,  9],
       [ 4,  8, 13],
       [ 7, 12, 18],
       [11, 17, 24],
       [16, 23, 31],
       [22, 30, 39],
       [29, 38, 48],
       [37, 47, 58],
       [46, 57, 69],
       [56, 68, 81]])

In [891]:
#M aking first col
num = 1
col = []
for i in range(0,10):
    col.append(i + num)
    num = i + num
    
# np.array(col).reshape(1001,1)
print(col)

[1, 2, 4, 7, 11, 16, 22, 29, 37, 46]


In [892]:
np.array(col).reshape(-1,1)

array([[ 1],
       [ 2],
       [ 4],
       [ 7],
       [11],
       [16],
       [22],
       [29],
       [37],
       [46]])

In [893]:
prison = np.array(col).reshape(-1,1)
adder = np.arange(2,12)

for k in range(0,10):
    loop_col = []
    
    for idx, val in enumerate(np.array(prison)):
        loop_col.append(val + adder[idx])
    
    adder += 1
    
    prison = np.concatenate((prison, np.array(loop_col).reshape(-1,1)),axis = 1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [886]:
prison

array([[ 1,  3],
       [ 2,  5],
       [ 4,  8],
       [ 7, 12],
       [11, 17],
       [16, 23],
       [22, 30],
       [29, 38],
       [37, 47],
       [46, 57],
       [56, 68]])

In [897]:
prison = np.array(col).reshape(-1,1)
adder = np.arange(2,12)

for k in range(0,10):
    loop_col = []
    
    for idx, val in enumerate(np.array(prison)[:,-1]):
        loop_col.append(val + adder[idx])
    
    adder += 1
    
    prison = np.concatenate((prison, np.array(loop_col).reshape(-1,1)),axis = 1)

In [898]:
prison

array([[  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66],
       [  2,   5,   9,  14,  20,  27,  35,  44,  54,  65,  77],
       [  4,   8,  13,  19,  26,  34,  43,  53,  64,  76,  89],
       [  7,  12,  18,  25,  33,  42,  52,  63,  75,  88, 102],
       [ 11,  17,  24,  32,  41,  51,  62,  74,  87, 101, 116],
       [ 16,  23,  31,  40,  50,  61,  73,  86, 100, 115, 131],
       [ 22,  30,  39,  49,  60,  72,  85,  99, 114, 130, 147],
       [ 29,  38,  48,  59,  71,  84,  98, 113, 129, 146, 164],
       [ 37,  47,  58,  70,  83,  97, 112, 128, 145, 163, 182],
       [ 46,  57,  69,  82,  96, 111, 127, 144, 162, 181, 201]])

In [926]:
##### This makes the prison
#Making first col
num = 1
col = []
for i in range(0,1000):
    col.append(i + num)
    num = i + num
    
# np.array(col).reshape(1001,1)
# print(col)

prison = np.array(col).reshape(-1,1)
adder = np.arange(2,1002)

for k in range(0,999):
    loop_col = []
    
    for idx, val in enumerate(np.array(prison)[:,-1]):
        loop_col.append(val + adder[idx])
    
    adder += 1
    
    prison = np.concatenate((prison, np.array(loop_col).reshape(-1,1)),axis = 1)

In [927]:
prison.shape

(1000, 1000)

In [934]:
prison[2,1]

8

In [1]:
def answer(x, y):
    
    import numpy as np
    
    # Making first column of the "prison" of the form [1,2,4,7,11,16,...]
    num = 1
    col = []
    for i in range(0,1000):
        col.append(i + num)
        num = i + num

        
    # Using the first column, building the rest of the "prison" column-by-column
    prison = np.array(col).reshape(-1,1)
    adder = np.arange(2,1002)

    for k in range(0,999):
        loop_col = []

        for idx, val in enumerate(np.array(prison)[:,-1]):
            loop_col.append(val + adder[idx])

        adder += 1

        prison = np.concatenate((prison, np.array(loop_col).reshape(-1,1)),axis = 1)
    
    return str(prison[y-1,x-1])

In [2]:
answer(1,1)

'1'

In [3]:
answer(3,2)

'9'

In [4]:
answer(2,3)

'8'

In [5]:
answer(5,10)

'96'

In [946]:
from array import *

In [176]:
##### This makes the prison
#Making first col, trying without using numpy
num = 1
col = []
for i in range(0,10):
    col.append(i + num)
    num = i + num
    
# np.array(col).reshape(1001,1)
# print(col)

prison = [col]
adder = list(range(2,12))
counter = 0

for k in range(0,9):
    loop_col = []
    
    for idx, val in enumerate(prison[0 + counter]):
        loop_col.append(val + adder[idx])
    
    
    for idx, val in enumerate(adder):
        adder[idx] = adder[idx] + 1
        
    counter += 1
    
    prison.append(loop_col)

In [177]:
prison

[[1, 2, 4, 7, 11, 16, 22, 29, 37, 46],
 [3, 5, 8, 12, 17, 23, 30, 38, 47, 57],
 [6, 9, 13, 18, 24, 31, 39, 48, 58, 69],
 [10, 14, 19, 25, 32, 40, 49, 59, 70, 82],
 [15, 20, 26, 33, 41, 50, 60, 71, 83, 96],
 [21, 27, 34, 42, 51, 61, 72, 84, 97, 111],
 [28, 35, 43, 52, 62, 73, 85, 98, 112, 127],
 [36, 44, 53, 63, 74, 86, 99, 113, 128, 144],
 [45, 54, 64, 75, 87, 100, 114, 129, 145, 162],
 [55, 65, 76, 88, 101, 115, 130, 146, 163, 181]]

In [178]:
len(prison)

10

In [179]:
len(prison[0])

10

In [170]:
transpose = []

col_idx = 0

while col_idx < 10:
    cell = []
    for row_idx, val in enumerate(prison):
#         print(row_idx)
        cell.append(prison[row_idx][col_idx])
#     print(col_idx, cell)
    transpose.append(cell)
    col_idx += 1
    
transpose

[[1, 3, 6, 10, 15, 21, 28, 36, 45, 55],
 [2, 5, 9, 14, 20, 27, 35, 44, 54, 65],
 [4, 8, 13, 19, 26, 34, 43, 53, 64, 76],
 [7, 12, 18, 25, 33, 42, 52, 63, 75, 88],
 [11, 17, 24, 32, 41, 51, 62, 74, 87, 101],
 [16, 23, 31, 40, 50, 61, 73, 86, 100, 115],
 [22, 30, 39, 49, 60, 72, 85, 99, 114, 130],
 [29, 38, 48, 59, 71, 84, 98, 113, 129, 146],
 [37, 47, 58, 70, 83, 97, 112, 128, 145, 163],
 [46, 57, 69, 82, 96, 111, 127, 144, 162, 181]]

In [98]:
adder

[12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

In [69]:
adder

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [201]:
##### This makes the prison
#Making first col, trying without using numpy

N = 1000
num = 1
col = []
for i in range(0, N):
    col.append(i + num)
    num = i + num
    
# np.array(col).reshape(1001,1)
# print(col)

prison = [col]
adder = list(range(2, N + 2))
counter = 0

for k in range(0,N - 1):
    loop_col = []
    
    for idx, val in enumerate(prison[0 + counter]):
        loop_col.append(val + adder[idx])
    
    
    for idx, val in enumerate(adder):
        adder[idx] = adder[idx] + 1
        
    counter += 1
    
    prison.append(loop_col)

transpose = []

col_idx = 0

while col_idx < N :
    cell = []
    for row_idx, val in enumerate(prison):
#         print(row_idx)
        cell.append(prison[row_idx][col_idx])
#     print(col_idx, cell)
    transpose.append(cell)
    col_idx += 1

In [202]:
len(transpose)

100

In [203]:
len(transpose[0])

100

In [333]:
def answer(x, y):
    
##### This makes the "prison" nested list
## Note: NumPy is does not support Python 2.7, which is what Google Foo Bar evaluates solutions with.

# Making first column to begin building the nested list:

    N = 1000  # This is the i and j dimension of resulting nested list (similar to form of 1000x1000 square matrix)
    num = 1
    col = []
    for i in range(0, N):
        col.append(i + num)
        num = i + num

    prison = [col]  
    adder = list(range(2, N + 2))
    counter = 0

    for k in range(0, N - 1):   # Building the other columns of the prison, then appending them.
        loop_col = []

        for idx, val in enumerate(prison[0 + counter]):
            loop_col.append(val + adder[idx])


        for idx, val in enumerate(adder):
            adder[idx] = adder[idx] + 1

        counter += 1

        prison.append(loop_col)
        # Note: This "prison" is "upside-down" compared to problem prompt, but calling the indexes
        # will still be in the correct relative direction.
    
    # This comment below is for transposing "prison" for troubleshooting.
    
#     transpose = []

#     col_idx = 0

#     while col_idx < N :  # Piece-wise transpose of prison.
#         cell = []
#         for row_idx, val in enumerate(prison):
#     #         print(row_idx)
#             cell.append(prison[row_idx][col_idx])
#     #     print(col_idx, cell)
#         transpose.append(cell)
#         col_idx += 1
        
    return str(prison[x-1][y-1]), len(prison), len(prison[0]), prison[-1][-1]

In [334]:
answer(1,1)

('1', 1000, 1000, 1998001)

In [335]:
answer(3,2)

('9', 1000, 1000, 1998001)

In [336]:
answer(2,3)

('8', 1000, 1000, 1998001)

In [337]:
answer(5,10)

('96', 1000, 1000, 1998001)

In [28]:
def answer(x, y):
    
##### This makes the "prison" nested list
## Note: NumPy is does not support Python 2.7, which is what Google Foo Bar evaluates solutions with.

# Making first column to begin building the nested list:

    N = 10  # This is the i and j dimension of resulting nested list (similar to form of 1000x1000 square matrix)
    num = 1
    col = ()
    for i in range(0, N):
        col = col + (i + num,)
        num = i + num

    prison = (tuple(col),)  
    adder = tuple(range(2, N + 2))
    counter = 0
    print(len(prison))
    for k in range(0, N - 1):   # Building the other columns of the prison, then appending them.
        loop_col = ()

        for idx, val in enumerate(prison[0 + counter]):
            loop_col = loop_col + (val + adder[idx],)

        counter += 1
        
        adder = tuple(range(2+counter, N + 2))

        prison = prison + (tuple(loop_col),)
        # Note: This "prison" is "upside-down" compared to problem prompt, but calling the indexes
        # will still be in the correct relative direction.
    
    # This comment below is for transposing "prison" for troubleshooting.
    
#     transpose = []

#     col_idx = 0

#     while col_idx < N :  # Piece-wise transpose of prison.
#         cell = []
#         for row_idx, val in enumerate(prison):
#     #         print(row_idx)
#             cell.append(prison[row_idx][col_idx])
#     #     print(col_idx, cell)
#         transpose.append(cell)
#         col_idx += 1
        
    return str(prison[x-1][y-1])

In [29]:
answer(1,1)

1


IndexError: tuple index out of range

In [67]:
N = 10000  # This is the i and j dimension of resulting nested list (similar to form of 1000x1000 square matrix)
num = 1
col = ()
for i in range(0, N):
    col = col + (i + num,)
    num = i + num

prison = (tuple(col),)
adder = tuple(range(2, N + 2))
counter = 0
# print(prison)
for k in range(0, N - 1):   # Building the other columns of the prison, then appending them.
    loop_col = ()

    for idx, val in enumerate(prison[0 + counter]):
#         print(val + adder[idx])
        loop_col = loop_col + (val + adder[idx],)
#     print(loop_col)
    
    prison = prison + (tuple(loop_col),)
    
    counter += 1

    adder = tuple(range(2+counter, N + 2 + counter))
    
# prison

KeyboardInterrupt: 

In [53]:
tuple(range(2+2, N + 2 + 2))

(4, 5, 6, 7, 8, 9, 10, 11, 12, 13)

In [31]:
N = 1000  # This is the i and j dimension of resulting nested list (similar to form of 1000x1000 square matrix)
num = 1
col = ()
for i in range(0, N):
    col = col + (i + num,)
    num = i + num

In [32]:
len(col)

1000

In [35]:
(tuple(col),)

((1,
  2,
  4,
  7,
  11,
  16,
  22,
  29,
  37,
  46,
  56,
  67,
  79,
  92,
  106,
  121,
  137,
  154,
  172,
  191,
  211,
  232,
  254,
  277,
  301,
  326,
  352,
  379,
  407,
  436,
  466,
  497,
  529,
  562,
  596,
  631,
  667,
  704,
  742,
  781,
  821,
  862,
  904,
  947,
  991,
  1036,
  1082,
  1129,
  1177,
  1226,
  1276,
  1327,
  1379,
  1432,
  1486,
  1541,
  1597,
  1654,
  1712,
  1771,
  1831,
  1892,
  1954,
  2017,
  2081,
  2146,
  2212,
  2279,
  2347,
  2416,
  2486,
  2557,
  2629,
  2702,
  2776,
  2851,
  2927,
  3004,
  3082,
  3161,
  3241,
  3322,
  3404,
  3487,
  3571,
  3656,
  3742,
  3829,
  3917,
  4006,
  4096,
  4187,
  4279,
  4372,
  4466,
  4561,
  4657,
  4754,
  4852,
  4951,
  5051,
  5152,
  5254,
  5357,
  5461,
  5566,
  5672,
  5779,
  5887,
  5996,
  6106,
  6217,
  6329,
  6442,
  6556,
  6671,
  6787,
  6904,
  7022,
  7141,
  7261,
  7382,
  7504,
  7627,
  7751,
  7876,
  8002,
  8129,
  8257,
  8386,
  8516,
  8647,
  8779,

In [23]:
(tuple(col),) + (tuple(col),)

((1,
  2,
  4,
  7,
  11,
  16,
  22,
  29,
  37,
  46,
  56,
  67,
  79,
  92,
  106,
  121,
  137,
  154,
  172,
  191,
  211,
  232,
  254,
  277,
  301,
  326,
  352,
  379,
  407,
  436,
  466,
  497,
  529,
  562,
  596,
  631,
  667,
  704,
  742,
  781,
  821,
  862,
  904,
  947,
  991,
  1036,
  1082,
  1129,
  1177,
  1226,
  1276,
  1327,
  1379,
  1432,
  1486,
  1541,
  1597,
  1654,
  1712,
  1771,
  1831,
  1892,
  1954,
  2017,
  2081,
  2146,
  2212,
  2279,
  2347,
  2416,
  2486,
  2557,
  2629,
  2702,
  2776,
  2851,
  2927,
  3004,
  3082,
  3161,
  3241,
  3322,
  3404,
  3487,
  3571,
  3656,
  3742,
  3829,
  3917,
  4006,
  4096,
  4187,
  4279,
  4372,
  4466,
  4561,
  4657,
  4754,
  4852,
  4951,
  5051,
  5152,
  5254,
  5357,
  5461,
  5566,
  5672,
  5779,
  5887,
  5996,
  6106,
  6217,
  6329,
  6442,
  6556,
  6671,
  6787,
  6904,
  7022,
  7141,
  7261,
  7382,
  7504,
  7627,
  7751,
  7876,
  8002,
  8129,
  8257,
  8386,
  8516,
  8647,
  8779,

In [13]:
() + (3,)

(3,)

In [112]:
def answer(x, y):
    
##### This makes the "prison" nested list
## Note: NumPy is does not support Python 2.7, which is what Google Foo Bar evaluates solutions with.

# Making first column to begin building the nested list:
    if x > y:
        N = x
    elif y > x:
        N = y
    elif y == x:
        N = x

#     N = 10000  # This is the i and j dimension of resulting nested list (similar to form of 1000x1000 square matrix)
    num = 1
    col = ()
    for i in range(0, N):
        col = col + (i + num,)
        num = i + num

    prison = (tuple(col),)
    adder = tuple(range(2, N + 2))
    counter = x

    
    
    
  # Building the other columns of the prison, then appending them.
    loop_col = ()

    loop_col = (col[x] + c[idx],)
    #     print(loop_col)

        prison = prison + (tuple(loop_col),)

        counter += 1

        adder = tuple(range(2+counter, N + 2 + counter))
    
# prison
        # Note: This "prison" is "upside-down" compared to problem prompt, but calling the indexes
        # will still be in the correct relative direction.
    
    # This comment below is for transposing "prison" for troubleshooting.
    
#     transpose = []

#     col_idx = 0

#     while col_idx < N :  # Piece-wise transpose of prison.
#         cell = []
#         for row_idx, val in enumerate(prison):
#     #         print(row_idx)
#             cell.append(prison[row_idx][col_idx])
#     #     print(col_idx, cell)
#         transpose.append(cell)
#         col_idx += 1
        
    return str(prison[x-1][y-1])

In [113]:
answer(1,1)

'1'

In [114]:
answer(3,2)

'9'

In [115]:
answer(5,10)

'96'

In [116]:
answer(100000,10)

KeyboardInterrupt: 

In [117]:
N = 100000
col = ()
for i in range(0, N):
    col = col + (i + num,)
    num = i + num

In [118]:
col

(5050449451,
 5050449452,
 5050449454,
 5050449457,
 5050449461,
 5050449466,
 5050449472,
 5050449479,
 5050449487,
 5050449496,
 5050449506,
 5050449517,
 5050449529,
 5050449542,
 5050449556,
 5050449571,
 5050449587,
 5050449604,
 5050449622,
 5050449641,
 5050449661,
 5050449682,
 5050449704,
 5050449727,
 5050449751,
 5050449776,
 5050449802,
 5050449829,
 5050449857,
 5050449886,
 5050449916,
 5050449947,
 5050449979,
 5050450012,
 5050450046,
 5050450081,
 5050450117,
 5050450154,
 5050450192,
 5050450231,
 5050450271,
 5050450312,
 5050450354,
 5050450397,
 5050450441,
 5050450486,
 5050450532,
 5050450579,
 5050450627,
 5050450676,
 5050450726,
 5050450777,
 5050450829,
 5050450882,
 5050450936,
 5050450991,
 5050451047,
 5050451104,
 5050451162,
 5050451221,
 5050451281,
 5050451342,
 5050451404,
 5050451467,
 5050451531,
 5050451596,
 5050451662,
 5050451729,
 5050451797,
 5050451866,
 5050451936,
 5050452007,
 5050452079,
 5050452152,
 5050452226,
 5050452301,
 5050452377,

In [91]:
map(col, )

TypeError: can only concatenate tuple (not "int") to tuple

In [121]:
N = 10
col = []
num = 1
for i in range(0, N):
    col.append(i + num)
    num = i + num

In [122]:
col

[1, 2, 4, 7, 11, 16, 22, 29, 37, 46]

In [123]:
col

[1, 2, 4, 7, 11, 16, 22, 29, 37, 46]

In [171]:
counter = 0
adder = tuple(range(2 + counter, N + 2 + counter))

In [172]:
adder

(2, 3, 4, 5, 6, 7, 8, 9, 10, 11)

In [176]:
range(4,N)[0]

4

In [183]:
col[2] + range(4,N)[0] + range(4,N)[1]  # can I just calculate only the number i want to look up?

13

In [196]:
col[3] + sum(range(col[2],5))

11

In [225]:
col = []
for n in range(1,100000):
    col.append(int(n*(n+1)/2 + 1))

In [ ]:
[[1, 3, 6, 10, 15, 21, 28, 36, 45, 55],
 [2, 5, 9, 14, 20, 27, 35, 44, 54, 65],
 [4, 8, 13, 19, 26, 34, 43, 53, 64, 76],
 [7, 12, 18, 25, 33, 42, 52, 63, 75, 88],
 [11, 17, 24, 32, 41, 51, 62, 74, 87, 101],
 [16, 23, 31, 40, 50, 61, 73, 86, 100, 115],
 [22, 30, 39, 49, 60, 72, 85, 99, 114, 130],
 [29, 38, 48, 59, 71, 84, 98, 113, 129, 146],
 [37, 47, 58, 70, 83, 97, 112, 128, 145, 163],
 [46, 57, 69, 82, 96, 111, 127, 144, 162, 181]]

In [ ]:
# num = 1
# col = ()
# for i in range(0, N):
#     col = col + (i + num,)
#     num = i + num

prison = [col]

# print(prison)



In [230]:
def answer(x, y):
    
##### This makes the "prison" nested list
## Note: NumPy is does not support Python 2.7, which is what Google Foo Bar evaluates solutions with.

# Making first column to begin building the nested list:
    N = 100000
    col = []
    for n in range(1,N):
        col.append(int(n*(n+1)/2 + 1))

    prison = [col]  
    adder = list(range(2, N + 2))
    counter = 0

    for k in range(0, N - 1):   # Building the other columns of the prison, then appending them.
        loop_col = []

        for idx, val in enumerate(prison[0 + counter]):
            loop_col.append(val + adder[idx])


        for idx, val in enumerate(adder):
            adder[idx] = adder[idx] + 1

        counter += 1

        prison.append(loop_col)
        # Note: This "prison" is "upside-down" compared to problem prompt, but calling the indexes
        # will still be in the correct relative direction.
    
    # This comment below is for transposing "prison" for troubleshooting.
    
#     transpose = []

#     col_idx = 0

#     while col_idx < N :  # Piece-wise transpose of prison.
#         cell = []
#         for row_idx, val in enumerate(prison):
#     #         print(row_idx)
#             cell.append(prison[row_idx][col_idx])
#     #     print(col_idx, cell)
#         transpose.append(cell)
#         col_idx += 1
        
    return str(prison[x-1][y-1]), len(prison), len(prison[0]), prison[-1][-1]

In [231]:
answer(1,1)

KeyboardInterrupt: 

In [275]:
col = []
for n in range(1,11):
    col.append(int(n*(n+1)/2))
col

[1, 3, 6, 10, 15, 21, 28, 36, 45, 55]

In [251]:
col = []
for n in range(2,12):
    col.append(int(n*(n+1)/2) - 1)
col

[2, 5, 9, 14, 20, 27, 35, 44, 54, 65]

In [253]:
col = []
for n in range(3,13):
    col.append(int(n*(n+1)/2) - 2)
col

[4, 8, 13, 19, 26, 34, 43, 53, 64, 76]

In [254]:
col = []
for n in range(4,14):
    col.append(int(n*(n+1)/2) - 3)
col

[7, 12, 18, 25, 33, 42, 52, 63, 75, 88]

In [312]:
col = []
for n in range(5,14):
    col.append(int(n*(n+1)/2) - 4)
col

[11, 17, 24, 32, 41, 51, 62, 74, 87]

In [337]:
col = []
for n in range(0,10):
    col.append(int(n*(n+1)/2) + 1)
col

[1, 2, 4, 7, 11, 16, 22, 29, 37, 46]

In [344]:
col = []
for n in range(1,11):
    col.append(int(n*(n+1)/2) + 2)
col

[3, 5, 8, 12, 17, 23, 30, 38, 47, 57]

In [345]:
col = []
for n in range(2,12):
    col.append(int(n*(n+1)/2) + 3)
col

[6, 9, 13, 18, 24, 31, 39, 48, 58, 69]

In [330]:
x = 3
y = 2

print()

[4, 7, 11, 16, 22, 29, 37, 46, 56, 67]

In [348]:
y_col = [(int(n*(n+1)/2) + 1) for n in range(0,10)]

In [349]:
y_col

[1, 2, 4, 7, 11, 16, 22, 29, 37, 46]

In [352]:
x_start = y_col[y-1]

x_start

2

In [372]:
col = []
for n in range(x_start,10 + x_start - 1):
    col.append(int(n*(n+1)/2) - 1)
col

[2, 5, 9, 14, 20, 27, 35, 44, 54]

In [371]:
[(int(n*(n+1)/2) - 1) for n in range(x_start,10 + x_start - 1)]

[2, 5, 9, 14, 20, 27, 35, 44, 54]

In [369]:
col[x - 1]

9

In [394]:
x = 3
y = 2

y_col = [(int(n*(n+1)/2) + 1) for n in range(0,10)]

x_start = y_col[y-1]

look_up = [(int(n*(n+1)/2) - 1) for n in range(x_start,10 + x_start - 1)]

print(x_start)
print(look_up)
print(look_up[x-1])

2
[2, 5, 9, 14, 20, 27, 35, 44, 54]
9


In [468]:
x = 2
y = 3

y_col = [(int(n*(n+1)/2) + 1) for n in range(0,10)]

# x_start = y_col[y-1]

look_up = [int(n*(n+1)/2 - (y-1)) for n in range(y,11)]

print(y_col)
# print(x_start)
print(look_up)
print(look_up[x-1])

[1, 2, 4, 7, 11, 16, 22, 29, 37, 46]
[4, 8, 13, 19, 26, 34, 43, 53]
8


In [464]:
y -1

2

In [422]:
col = []
for n in range(1,10):
    col.append(int(n*(n+1)/2))
col

[1, 3, 6, 10, 15, 21, 28, 36, 45]

In [429]:
col = []
for n in range(2,10):
    col.append(int(n*(n+1)/2) - 1)
col

[2, 5, 9, 14, 20, 27, 35, 44]

In [431]:
col = []
for n in range(3,13):
    col.append(int(n*(n+1)/2) - 2)
col

[4, 8, 13, 19, 26, 34, 43, 53, 64, 76]

In [433]:
[int(n*(n+1)/2) for n in range(1,10)]

[1, 3, 6, 10, 15, 21, 28, 36, 45]

In [434]:
[int(n*(n+1)/2 - 1) for n in range(1 + 1,10 + 1)]

[2, 5, 9, 14, 20, 27, 35, 44, 54]

In [435]:
[int(n*(n+1)/2 - 2) for n in range(1 + 2,10 + 2)]

[4, 8, 13, 19, 26, 34, 43, 53, 64]

In [475]:
x = 5
y = 10

y_col = [(int(n*(n+1)/2) + 1) for n in range(0,100)]

# x_start = y_col[y-1]

look_up = [int(n*(n+1)/2 - (y-1)) for n in range(y,101)]

# print(y_col)
# # print(x_start)
# print(look_up)
print(look_up[x-1])

96


In [491]:
x = 10
y = 5

y_col = [(int(n*(n+1)/2) + 1) for n in range(0,100001)]

# x_start = y_col[y-1]

look_up = [int(n*(n+1)/2 - (y-1)) for n in range(y, y + 100000)]

# print(y_col)
# # print(x_start)
# print(look_up)
print(look_up[x-1])

101


In [483]:
look_up

[4999950001]

In [499]:
def answer(x, y):
    
    # Checking vertical column of prison first:
    y_col = [(int(n*(n+1)/2) + 1) for n in range(0,100001)]
    
    # Checking horizontal column of prison second:
    look_up = [int(n*(n+1)/2 - (y-1)) for n in range(y, y + 100000)]

    return(str(look_up[x-1]))

In [500]:
# # Test Cases:
# answer(1,1)

# answer(2,3)

# answer(3,2)

# answer(5,10)

# answer(10,5)

# answer(100000, 100000)

'1'