Fuel Injection Perfection
=========================

Commander Lambda has asked for your help to refine the automatic quantum antimatter fuel injection system for her LAMBCHOP doomsday device. It's a great chance for you to get a closer look at the LAMBCHOP - and maybe sneak in a bit of sabotage while you're at it - so you took the job gladly. 

Quantum antimatter fuel comes in small pellets, which is convenient since the many moving parts of the LAMBCHOP each need to be fed fuel one pellet at a time. However, minions dump pellets in bulk into the fuel intake. You need to figure out the most efficient way to sort and shift the pellets down to a single pellet at a time. 

The fuel control mechanisms have three operations: 

1) Add one fuel pellet
2) Remove one fuel pellet
3) Divide the entire group of fuel pellets by 2 (due to the destructive energy released when a quantum antimatter pellet is cut in half, the safety controls will only allow this to happen if there is an even number of pellets)

Write a function called answer(n) which takes a positive integer as a string and returns the minimum number of operations needed to transform the number of pellets to 1. The fuel intake control panel can only display a number up to 309 digits long, so there won't ever be more pellets than you can express in that many digits.

For example:
answer(4) returns 2: 4 -> 2 -> 1
answer(15) returns 5: 15 -> 16 -> 8 -> 4 -> 2 -> 1


Languages
=========

To provide a Python solution, edit solution.py
To provide a Java solution, edit solution.java

Test cases
==========

Inputs:
    (string) n = "4"
Output:
    (int) 2

Inputs:
    (string) n = "15"
Output:
    (int) 5

In [1]:
def answer(n):
    
    current = int(n)
    n_operations = 0
    
    if n == 1:
        return 1
    
    while current != 1:
    
        if current == 1:
            break

        elif current%2 == 0:
            
            current = current / 2
            n_operations += 1
#             print(current*2,"(/2)  ", current, n_operations)
            
        elif current%2 == 1:
            
            if ((current-1)/2) % 2 == 0 or (current-1)/2 == 1:
                
                current -= 1
                n_operations += 1
#                 print(current+1, "(-1)  ", current, n_operations)
            
            elif ((current+1)/2) % 2 == 0:
                
                current += 1
                n_operations += 1
#                 print(current-1, "(+1)  ", current, n_operations)
            
#     print("Total # operations:", n_operations)
    return n_operations

In [2]:
answer(15)

5

In [3]:
answer(25)

6

In [4]:
answer(6)

3

In [5]:
answer(11)

5

In [6]:
answer(3)

2

Prepare the Bunnies' Escape
===========================

You're awfully close to destroying the LAMBCHOP doomsday device and freeing Commander Lambda's bunny prisoners, but once they're free of the prison blocks, the bunnies are going to need to escape Lambda's space station via the escape pods as quickly as possible. Unfortunately, the halls of the space station are a maze of corridors and dead ends that will be a deathtrap for the escaping bunnies. Fortunately, Commander Lambda has put you in charge of a remodeling project that will give you the opportunity to make things a little easier for the bunnies. Unfortunately (again), you can't just remove all obstacles between the bunnies and the escape pods - at most you can remove one wall per escape pod path, both to maintain structural integrity of the station and to avoid arousing Commander Lambda's suspicions. 

You have maps of parts of the space station, each starting at a prison exit and ending at the door to an escape pod. The map is represented as a matrix of 0s and 1s, where 0s are passable space and 1s are impassable walls. The door out of the prison is at the top left (0,0) and the door into an escape pod is at the bottom right (w-1,h-1). 

Write a function answer(map) that generates the length of the shortest path from the prison door to the escape pod, where you are allowed to remove one wall as part of your remodeling plans. The path length is the total number of nodes you pass through, counting both the entrance and exit nodes. The starting and ending positions are always passable (0). The map will always be solvable, though you may or may not need to remove a wall. The height and width of the map can be from 2 to 20. Moves can only be made in cardinal directions; no diagonal moves are allowed.

Languages
=========

To provide a Python solution, edit solution.py
To provide a Java solution, edit solution.java

Test cases
==========

Inputs:
    (int) maze = [[0, 1, 1, 0], [0, 0, 0, 1], [1, 1, 0, 0], [1, 1, 1, 0]]
Output:
    (int) 7

Inputs:
    (int) maze = [[0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 0], [0, 0, 0, 0, 0, 0], [0, 1, 1, 1, 1, 1], [0, 1, 1, 1, 1, 1], [0, 0, 0, 0, 0, 0]]
Output:
    (int) 11

In [11]:
import numpy as np

In [12]:
test1 = np.array([[0, 1, 1, 0], [0, 0, 0, 1], [1, 1, 0, 0], [1, 1, 1, 0]])

In [13]:
test1

array([[0, 1, 1, 0],
       [0, 0, 0, 1],
       [1, 1, 0, 0],
       [1, 1, 1, 0]])

In [14]:
test2 = np.array([[0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 0], [0, 0, 0, 0, 0, 0], [0, 1, 1, 1, 1, 1], [0, 1, 1, 1, 1, 1], [0, 0, 0, 0, 0, 0]])

In [32]:
test2

array([[0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0]])

In [17]:
test0 = [[0,0],[0,0]]

In [33]:
steps = 0

i_loc = 0
j_loc = 0

wall_remove = False

loop_row = []
matrix = []

for i, row in enumerate(test1):

    for j, col in enumerate(row):
        
        print(j,col)


0 0
1 1
2 1
3 0
0 0
1 0
2 0
3 1
0 1
1 1
2 0
3 0
0 1
1 1
2 1
3 0


In [34]:
test1

array([[0, 1, 1, 0],
       [0, 0, 0, 1],
       [1, 1, 0, 0],
       [1, 1, 1, 0]])

In [36]:
len(test1[0])

4

In [133]:
# maze = [[0, 1, 1, 0], [0, 0, 0, 1], [1, 1, 0, 0], [1, 1, 1, 0]]
# maze = [[0,1,0],[0,1,0],[0,0,0]]
maze = test2  #should be solved in ~20 steps without removing walls.

row_end = len(maze[0])
col_end = len(maze)

steps = 0

i = 0
j = 0

left_walk = True

wall_remove = False

loop_row = []
matrix = []

print(i,j, steps)

while i < row_end and j < col_end:

    if j+1 < row_end and left_walk == True: #not sure if this needs to be j + 1 in col_end = len(maze), off by 1?
        
        if maze[i][j+1] == 0:
            j += 1
            steps += 1
            print('moved right')
            print(i,j,steps)
            
            
        elif maze[i][j+1] == 1:
            print('found wall to my right')
            pass
            
    if i+1 < col_end:

        if maze[i+1][j] == 0:
            i += 1
            steps += 1
            print('moved down')
            print(i,j,steps)
            left_walk = True
            
        elif maze[i+1][j] == 1 and maze[i][j-1] == 0:
            print('found wall below')
            left_walk = False
            j -= 1
            steps += 1
            print(i,j,steps)
            pass
    
#     if i+1 < col_end and j+1 < col_end and i > 0 and j > 0:
        
#         if maze[i][j+1] == 1 and maze[i+1][j] == 1:

#             i -= 2
#             steps += 1
#             print('found corner')
                     
    if i == row_end-1 and j == col_end-1:
        
        print("Found Exit")
        print(i,j,steps)
        break
        
print("\nSolved maze in",steps, "steps")

0 0 0
moved right
0 1 1
found wall below
0 0 2
found wall below
0 -1 3
moved down
1 -1 4
found wall to my right
moved down
2 -1 5
moved right
2 0 6
moved down
3 0 7
found wall to my right
moved down
4 0 8
found wall to my right
moved down
5 0 9
moved right
5 1 10
moved right
5 2 11
moved right
5 3 12
moved right
5 4 13
moved right
5 5 14
Found Exit
5 5 14

Solved maze in 14 steps


In [104]:
i

2

In [115]:
col_end

6

In [42]:
try:
    sds
    print('foo')
except:
    print('bar')

bar


In [82]:
maze[0][1]

1